name: checkov
on:
  workflow_run:
    workflows:
      - tests
    types:
      - completed
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Scan with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          skip_check: CKV_AWS_130
          framework: terraform
