name: release
on:
  workflow_run:
    workflows: ["checkov"]
    types:
      - completed
jobs:
  release:
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: "marvinpinto/action-automatic-releases@v1.1.2"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: latest
